#
# Personal Website
# 
site_name: Zhang Zhou's website
site_url: https://zhangzhou.site/ # must have the trailing slash
site_author: Zhang Zhou(jason_zhang_03@icloud.com)
site_description: Interesting little things in my life and learning process.
copyright: > # should remain a link to the original theme
  &copy; 2023-2023 Zhang Zhou's website<br>
  <a href="https://github.com/Sputnik103/my-docs">Blog Theme</a> /
  <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>
nav:
  - Home: index.md
  - About: about/index.md
  - Blog: 
    - blog/index.md
    - バイト（打工）:
      - 咨询实习: blog/intern/consulting.md
      - 互联网实习: blog/intern/internet.md
      - 金融实习: blog/intern/finance.md
    - 旅行:
      - 解封后旅行（回忆版）: blog/travel/travel_after_covid.md
      - 毕业旅行——霓虹: blog/travel/graduation_travel.md
  - Projects: 
    - projects/index.md
    - Selenium爬虫应用实例: projects/spider.md
  - Articles:
    - articles/index.md
    - Markdown常用格式: articles/markdown_template.md
  - Tags: tags/tags.md

#
# Theme settings
#
theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material

  # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  custom_dir: overrides

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:

    # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep orange
      # toggle:
      #   icon: material/brightness-7
      #   name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: deep orange
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode

  language: zh # 一些提示性的文字会变成中文
  logo: /assets/logo_light.gif

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Noto Serif
    code: Roboto Mono

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  # icon:
  #   logo: fontawesome/solid/code
  favicon: /assets/favicon3.png

  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # - navigation.instant # some features may not work properly with XHR
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level folders are shown as tabs
    # - navigation.tabs.sticky # tabs always show
    # - navigation.sections # second-level folders are expanded
    # - navigation.expand # all folders are expanded
    - navigation.top # 回到页面顶部
    # - toc.integrate # show the table of contents in the navigation panel
    
    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    # - search.suggest # display the likeliest completion for the last word
    # - search.highlight # highlight all occurrences
    # - search.share # show a share button of the current search

    # Header
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
    # - header.autohide # hide the post title when scroll down

    # Content
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # add comment to code blocks
    - content.tabs.link # link tabs with the same label

#
# Plugins
#
plugins:
  - search: # must be included at the first place
      lang:
        - en
        # 日语搜索汉字
        - ja
  # - mkdocs-video # 有点问题
  - glightbox:
      effect: zoom
      zoomable: true
      draggable: true
      skip_classes:
        - nonzoom
  # - tags: # we have our own internal tag feature
        # tags_file: tags.md # generated links do not work
  - awesome-pages:
      # collapse_single_pages: true # replaced by navigation.indexes
  # - section-index # must be after awesome-pages, replaced by navigation.indexes
  - git-revision-date-localized:
        enable_creation_date: true
        fallback_to_build_date: true
        type: iso_date
  - encryptcontent:
        hljs: false
        arithmatex: false
        mermaid2: false
        password_button: true
        remember_password: true
        default_expire_dalay: 24
        # reload_scripts:
            # - "./assets/extra.js"
  - exclude:
        glob:
          - '*/exclude/*'
        regex:
          - '.*\[exclude\].*'
  # - pdf-with-js:
        # enable: false # should enable only when need PDF files
        # add_download_button: false
        # display_header_footer: true
        # header_template: >-
            # <div style="font-size:8px; margin:auto; color:lightgray;">
                # <span class="title"></span>
            # </div>
        # footer_template: >-
            # <div style="font-size:8px; margin:auto; color:lightgray;">
                # Page <span class="pageNumber"></span> of 
                # <span class="totalPages"></span>
            # </div>

#
# Extensions
#
markdown_extensions:
  #
  # Python Markdown
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  #
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks (!!!info等)
  - attr_list # allow to add HTML attributes and CSS classes  # 给图片后面添加{width="300"}设置大小
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  - toc: # generate a table of contents from documents
      permalink: '#' # anchor
      toc_depth: 4 # header 1 to header 4
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true

  #
  # Python Markdown Extensions
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  #
  - pymdownx.arithmatex: # render math equations
      generic: true
  # - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      # smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis 
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # define code blocks and nesting of code
  - pymdownx.highlight: # highlight of code blocks
      linenums_style: pymdownx-inline
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks
  - pymdownx.smartsymbols # convert some sequences of characters into their corresponding symbols
  - pymdownx.snippets: #  embed content from arbitrary files into a document
      check_paths: true
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  # - pymdownx.keys # syntax ++ctrl+c++ does not look clear in MD document
  - pymdownx.progressbar

  #
  # Extra extensions
  #
  - markdown_captions # add caption to figures
  - customblocks # use ::: to create a new <div>
  # - cell_row_span # merge cells in a table
  # - kbdextension # syntax [[ctrl]][[c]] does not look clear in MD document

#
# Extras
#
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
  analytics:
    provider: google
    property: G-144Q0VJMBT
    # property: UA-42618265-2
  
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#cookie-consent
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  
  disqus: "Sputnik103-github-io"
  
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sputnik103
      name: GitHub | Sputnik103
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/13132391
      name: BiliBili | Jason_ZZ
  generator: false # hide the line "Made with Material for MkDocs"

extra_css:
  - /assets/extra.css
  - /assets/custom-image-grid.css # 实现图片网格（暂时不启用，在手机和safari上显示存在问题）
  - /assets/image_video.css # 实现图片视频居中和大小调节
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js