site_name: Zhang Zhou's website
nav:
  - 主页: index.md
  - About me ...:   
    - hello.md
  - Python随想录: 
    - Selenium爬虫应用实例: python_cases/spider.md
  - Markdown相关:
    - Markdown常用格式: markdown/markdown_template.md
  - 生活记录: 
    - 毕业旅行——霓虹: life/毕业旅行.md
theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material

  # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  custom_dir: overrides

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: zh # 一些提示性的文字会变成中文
  logo: assets/logo.png

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Noto Serif
    code: Roboto Mono

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  favicon: favicon.png
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js